### PR TITLE
Improved rendering on hi-res displays by using SVG faceplates

### PR DESCRIPTION
**Pull request by evmaki**
PNG was originally the file format used for the faceplates due to problems rendering the complex patterns on some of the modules as SVG. After some investigation, I found the problem could be eliminated by avoiding the use of "compound paths" in the SVG files.

- Where appropriate, compound paths have been replaced with regular paths.
- Source files have been slightly altered to reflect the change. Most now use `setPanel`. Tides still uses `addChild` but the type of the panels is changed from `Panel` to `SVGPanel`.
- Illustrator and SVG formats are included. Both contain a layer for the faceplate, a layer for the original cut lines, and a layer for widget placement. The cut line and widget layers should probably be removed from the production SVGs to save on file size and potential memory overhead.

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Needed a Tweet https://twitter.com/vcvrack/status/973479311759085568

**Comment by evmaki** [comment]
Thanks for the shoutout! I'm happy to do Peaks as well.

**Comment by AndrewBelt** [comment]
Mind doing the Plaits panel? It'll be called "Macro Oscillator 2" with slug "Plaits". Email contact@vcvrack.com and I'll send the Illustrator file.

**Comment by evmaki** [comment]
Sure thing!

**Pull request merged**
