### PR TITLE
Initial version of Peaks.

### PR DESCRIPTION
**Pull request by cschol**
Port of Mutable Instruments Peaks a.k.a. "Percussive Synthesizer".

A few comments:

- The code tries to reuse as much functionality as possible from the original source and does not require any modifications of the eurorack submodule to build.
- However, most of the content of the ui.cpp file has been ported into the Peaks.cpp. It was easier than trying to recreate all that complex logic from scratch.
- The output scaling might be a little off. I unfortunately don't have an actual device to compare it, but maybe can look for someone to help test.
- I created the panel design from the Peaks.ai file in the repository (modified with Photoshop). I don't know how the other panel PNGs were created. Maybe this one can be re-created the same way. The locations of UI components should be accurate though according to the panel layout. It is missing the module name on the panel as I didn't know what font the other modules use.
- The only thing that was not possible to implement was the access to the "Number station" secret mode by pressing the two small buttons at the same time for three times. I implemented this by a context menu option. Same with the snap mode, which requires holding a button on power up.

### CODE REVIEW

**Comment by gbrandt1** [comment]
may i ask what's gonna happen with this? thanks!

**Comment by AndrewBelt** [comment]
It'll be included with Rack 0.6.

**Comment by evmaki** [comment]
FYI @cschol I believe the font used on the faceplates is DIN.

**Comment by cschol** [comment]
@evmaki Thanks. Andrew is taking care of the face plate.

**Comment by AndrewBelt** [comment]
This needs some work. `IOBuffer` isn't needed at all. Remove that, contain everything as member variables.

**Comment by cschol** [comment]
Peaks is somewhat of a weird multi-function module (LFO, Drum Synth, and others). Replacing those mode selection buttons with context menus does not make sense, in my opinion. The buttons allow switching between modes at runtime (to change settings in the other channel) and it would loose some of its quirky appeal if the buttons worked differently than in the real module. It is a little convoluted, but I thought I read somewhere that's partly why Olivier obsoleted it.

I tried removing the `IOBuffer` initially, but some of that code was pretty coupled and in the end it was easier to just port the whole thing. I did not want to introduce any weird bugs due to refactoring.

Let me know if you want me to work on this more.

**Comment by gbrandt1** [comment]
and before you remove parts of the code if you have the time you could maybe also to cast a brief look at the Dead Man's Catch alternative firmware - not to include in Rack, of course, but in terms of retaining capability of community implementation.

**Pull request merged**
