### PR TITLE
Initial version of Peaks.

### PR DESCRIPTION
**Pull request by cschol**
Port of Mutable Instruments Peaks a.k.a. "Percussive Synthesizer".

A few comments:
- The code tries to reuse as much functionality as possible from the original source and does not require any modifications of the `eurorack` submodule to build.
- However, most of the content of the `ui.cpp` file has been ported into the `Peaks.cpp`. It was easier than trying to recreate all that complex logic from scratch.
- The output scaling might be a little off. I unfortunately don't have an actual device to compare it, but maybe can look for someone to help test.
- I created the panel design from the `Peaks.ai` file in the repository (modified with Photoshop). I don't know how the other panel PNGs were created. Maybe this one can be re-created the same way. The locations of UI components should be accurate though according to the panel layout. It is missing the module name on the panel as I didn't know what font the other modules use.
- The only thing that was not possible to implement was the access to the "Number station" secret mode by pressing the two small buttons at the same time for three times. I implemented this by a context menu option. Same with the snap mode, which requires holding a button on power up.

### CODE REVIEW

**Comment by cschol** [comment]
@AndrewBelt I'll update this PR to the `v0.6` API in the next couple of days.

**Comment by AndrewBelt** [comment]
Don't worry about the panel, I'll do that.

**Comment by cschol** [comment]
Mmm...that PR didn't update as expected. I should have made the initial PR from a branch instead of `master`. I can redo the PR from the `peaks` branch if you want. That one includes all the latest `v0.6` API updates.

**Comment by cschol** [comment]
#45 is clean PR from `peaks` branch against `master`. Closing this one.

**Pull request closed without merging**
